---
title:  "Promise 객체"
last_modified_at: 2021-07-24:T14:25:52-05:00
categories:
  - Promise
tags:
  - 자바스크립트  
---

# Promise란?

프로미스란 하나의 값을 미래의 반환할 수도 있는 개체이다. 반환된 값은 resolved된 값이거나, resolve되지 못한(rejected) 이유일 것이다. 프로미스는 다음 3가지 상태중 하나일 것이다: fulfilled, rejected, pending. 프로미스 사용자는 프로미스를 다루기 위해 콜백 함수를 붙일 수 있다.

프로미스는 성실하다. 생성자가 실행되면 바로 주어진 작업을 한다. 게으른 작업이 필요하다면 observables (Rx.js) 혹은 tasks를 참고하라.

# Promise의 작동 방식

프로미스는 fullfilled이거나 rejected인 경우 settled되었다고 할 수 있다. Settle된 프로미스는 또 다시 settle 될 수 없다. 즉, 다시 resolve 혹은 reject를 호출 하는 것은 아무런 영향이 없다.

## ES6 Promise 생성자

- ES6 프로미스 생성자는 두개의 함수를 파라미터로 받는데, 첫 번째는 resolve이고 두 번째는 reject이다.
- resolve를 호출하면 fulfilled 상태가 되며 reject를 호출하면 rejected 상태가 된다.
- resolve, reject 호출시 value를 넣어줄 수 있는데, 이는 .then (혹은 .catch)에서 받을 수 있다.
    - reject시 아무런 값을 넣어줄 수 있지만 에러 객체를 넣는 걸 권장한다

## .then()

- .then은 프로미스 객체가 settled된 이후에 실행된다.
    - .then은 두 개의 함수를 파라미터로 받을 수 있는데
        - 첫 번째는 onFulfilled로, resolve시 호출된다.
        - 두 번째는 onRejected로, reject시 호출된다.
- .then은 같은 프로미스에 여러번 호출 될 수 있다.
- .then은 promise를 반환해야한다
    - onFullfilled 혹은 onRejected에서 반환된 `x`가 promise가 아니라면, 해당 .then에서 반환하는 값은 `x`의 값으로 fulfilled된 promise이다.
    - 

## Error Handling

- 앞서 봤듯이 then에서 onRejected에서 rejected된 에러를 핸들링할 수 있다.
- 그러나 이러한 방식은 문제가 존재한다.
- onFullFilled에서 에러가 발생시 해당 에러를 catch할 수 없다는 것이다.
- 이러한 이유로, 이러한 방식으로 에러를 핸들링하는 것은 anti-pattern으로 여겨지며, .catch를 이용하여 마지막에 에러를 핸들링하는 방식이 권장된다

## Promise의 추가적인 기능들

- Promise.race(): 프로미스의 배열을 받아서 해당 배열중에서 가장 먼저 resolved된 애 혹은 rejected된 애를 반환한다
- Promise.all(): 프로미스의 배열을 받아서 해당 프로미스가 전부 resolve된 후 resolve되거나 처음 reject된 프로미스의 에러로 reject하는 프로미스를 반환한다